version: '3'

services:
  web:
    build: . # This will use the Dockerfile in the current directory to build the image
    image: webdoors/martivia-web:latest
    container_name: web_container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: admin_martivia
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/admin_martivia.sql:/docker-entrypoint-initdb.d/admin_martivia.sql

volumes:
  db_data:
