version: '3'

services:
  web:
    image: php:7.4-apache
    container_name: web_container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_HOST: db

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: admin_martivia
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./admin_martivia.sql:/docker-entrypoint-initdb.d/admin_martivia.sql

volumes:
  db_data:
